apiVersion: apps/v1

kind: Deployment
metadata:
  name: {{ include "app.core.fullname" . }}
  labels:
    {{- include "app.core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.core.autoscaling.enabled }}
  replicas: {{ .Values.core.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.core.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        configmap.checksum: {{ include (print $.Template.BasePath "/core/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "app.core.labels" . | nindent 8 }}
        {{- with .Values.core.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.core.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.core.serviceAccountName" . }}
      {{- with .Values.core.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.core.storage.enabled }}
      volumes:
        - name: upload-storage
          persistentVolumeClaim:
            claimName: {{ include "app.core.fullname" . }}-upload-pvc
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.core.service.port }}
              protocol: TCP
          {{- with .Values.core.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.core.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.core.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.core.storage.enabled }}
          volumeMounts:
            - name: upload-storage
              mountPath: {{ .Values.core.storage.path }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "app.core.configMapName" . }}
            - secretRef:
                name: {{ include "app.core.database.secretName" . }}
            - secretRef:
                name: {{ include "app.core.gateway.secretName" . }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.core.database.secretName" . }}
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.core.database.secretName" . }}
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.core.configMapName" . }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.core.configMapName" . }}
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.core.configMapName" . }}
                  key: DB_NAME

            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
      {{- with .Values.core.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

